name: Publish To npm
# masterブランチにPushされた場合に実行する
on:
    push:
        branches:
            - master
        tags:
            - '!*'
    workflow_dispatch:
jobs:
    publish-to-npm:
        runs-on: ubuntu-latest
        # npmのTrusted Publisher（OIDC）で認証するため必要。gitタグ作成のため contents: write も付与
        permissions:
            contents: write
            id-token: write
        steps:
            # npmのTrusted Publisher設定（package側でGitHub Actionsを信頼）によりOIDC認証するため、NODE_AUTH_TOKENは不要
            # 注意: registry-urlを指定すると setup-node が GITHUB_TOKEN を npm 認証用に書き込み、OIDC より先に使われて E404 になるため指定しない
            - name: Checkout
              uses: actions/checkout@v3
            - name: Use Node.js And Setup .npmrc
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: npm
            # リリース可能か確認
            - name: Can Publish
              run: npx can-npm-publish --verbose
            - name: Install
              run: npm install
            - name: Build
              run: npm run build --if-present
            # リリース（スコープなしのパッケージ名 inputfollow.js として公開）
            - name: Publish
              run: npm publish
            # Push tag to GitHub if package.json version's tag is not tagged
            - name: package-version
              run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
            # Gitでリリースタグを作成
            - name: package-version-to-git-tag
              uses: pkgdeps/git-tag-action@v2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  github_repo: ${{ github.repository }}
                  version: ${{ env.PACKAGE_VERSION }}
                  git_commit_sha: ${{ github.sha }}
                  git_tag_prefix: 'v'
